```{r}

library(tidyverse)
library(rvest)
library(janitor)

url <- "https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132"

table <- url %>%
  read_html() %>% 
  html_node('table') %>%  
  html_table() %>% 
  as_tibble() %>% 
  set_names(.[1,]) %>%
  slice(-1) %>% 
  rename(modell = 'Modell (temp. varierte fra 0° til -10°)') %>% 
  rename(wltp = 'WLTP-tall') %>% 
  rename(stop = 'STOPP') %>% 
  rename(avvik = 'Avvik') %>% 
  separate(wltp, into = c("wltp1", "wltp2"), sep = "/", convert = TRUE, fill = "right") %>%
  mutate(wltp1 = as.numeric(gsub("[^0-9.]", "", wltp1)),
         stop = as.numeric(gsub("[^0-9.]", "", stop)))  # remove non-numeric characters and convert to numeric

```

```{r, warning=FALSE}
table %>% 
ggplot(aes(x = wltp1, y = stop)) +
  geom_point() +
  annotate("text", x=400, y=550, label= 'Cars are to be expected perform', color = 'red') +
  geom_abline(intercept = 0, slope = 1, color = "red") +
   labs(x = "WLPT-range(km)", y = "Actual-range(km)", title = 'Test results of electric cars', caption = 'https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132')
```

```{r}
lm(stop~wltp1, data = table)

```

```{r, warning=FALSE}
table %>% 
ggplot(aes(x = wltp1, y = stop)) +
  geom_point() +
  annotate("text", x=400, y=500, label= 'Cars are to be expected to perform', color = 'red') +
  annotate("text", x=600, y=400, label= 'Actual performance', color = 'blue')+
  geom_abline(intercept = 0, slope = 1, color = "red") +
  labs(x = "WLPT-range(km)", y = "Actual-range(km)", title = 'Test results of electric cars', caption = 'https://www.motor.no/aktuelt/motors-store-vintertest-av-rekkevidde-pa-elbiler/217132')+
  geom_smooth(method = lm)
```
